services:
  postgres:
    image: postgres:18-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-neohabit}"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-neohabit}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    volumes:
      - postgres:/var/lib/postgresql
    ports:
      # Exposes port 5433 just in case postgres is already running outside docker
      - "127.0.0.1:5433:5432"
    networks:
      - app-network

  backend:
    restart: unless-stopped
    image: ghcr.io/vsein/neohabit-back:${TAG:-test}
    # uncomment for building manually
    # build: ./backend
    # pull_policy: build
    depends_on:
      postgres:
        condition: service_healthy
    container_name: backend
    environment:
      PG_DSN: postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-password}@postgres:5432/${POSTGRES_DB:-neohabit}?sslmode=disable
      PG_MAX_OPEN_CONNS: ${PG_MAX_OPEN_CONNS:-10}
      PG_MAX_LIFETIME: ${PG_MAX_LIFETIME:-1h}
      PG_MAX_IDLE_TIME: ${PG_MAX_IDLE_TIME:-1h}
      # ADDRESS: 0.0.0.0:9000
      ADDRESS: ":9000"
      LOG_LEVEL: ${LOG_LEVEL:-info}
      JWT_SECRET: ${JWT_SECRET:-please_DONT_leave_blank}
    ports:
      - "127.0.0.1:9000:9000"
    networks:
      - app-network

  frontend:
    restart: unless-stopped
    image: ghcr.io/vsein/neohabit-front:${TAG:-test}
    # uncomment for building manually
    # build: ./frontend
    # pull_policy: build
    container_name: frontend
    environment:
      API_URL: ${API_URL:-http://127.0.0.1:9000/}
      DISABLE_SIGNUP: ${DISABLE_SIGNUP:-false}
      STRICT_USER_FIELDS: ${STRICT_USER_FIELDS:-false}
      REQUIRE_EMAIL: ${REQUIRE_EMAIL:-false}
    ports:
      - "${HOST:-127.0.0.1}:${HOST_PORT:-8080}:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres:
