services:
  postgres:
    image: postgres:18-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-neohabit}"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-neohabit}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    volumes:
      - postgres:/var/lib/postgresql        # in a volume
      # - ./data/postgres:/var/lib/postgresql # saves locally
      # NOTE: /var/lib/postgresql is recommended starting with postgres v18, it's not a mistake
    networks:
      - app-network

  backend:
    restart: unless-stopped
    image: ghcr.io/vsein/neohabit-back:${TAG:-latest}
    # Uncomment for building manually
    # build: ./backend
    # pull_policy: build
    depends_on:
      postgres:
        condition: service_healthy
    container_name: backend
    environment:
      PG_DSN: postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-password}@postgres:5432/${POSTGRES_DB:-neohabit}?sslmode=disable
      PG_MAX_OPEN_CONNS: ${PG_MAX_OPEN_CONNS:-10}
      PG_MAX_LIFETIME: ${PG_MAX_LIFETIME:-1h}
      PG_MAX_IDLE_TIME: ${PG_MAX_IDLE_TIME:-1h}
      LOG_LEVEL: ${LOG_LEVEL:-info}
      JWT_SECRET: ${JWT_SECRET:-please_DONT_leave_blank}
      FRONTEND_URL: ${FRONTEND_URL:-http://127.0.0.1:${FRONTEND_PORT:-8080}}
      ADDRESS: ":${BACKEND_PORT:-9000}"
    networks:
      - app-network

  frontend:
    restart: unless-stopped
    image: ghcr.io/vsein/neohabit-front:${TAG:-latest}
    # Uncomment for building manually
    # build: ./frontend
    # pull_policy: build
    container_name: frontend
    environment:
      DISABLE_SIGNUP: ${DISABLE_SIGNUP:-false}
      STRICT_USER_FIELDS: ${STRICT_USER_FIELDS:-false}
      REQUIRE_EMAIL: ${REQUIRE_EMAIL:-false}
      DEMO: false
    ports:
      # Local development â€“ only localhost (secure)
      - "127.0.0.1:${FRONTEND_PORT:-8080}:80"

      # Uncomment only when deploying to a real server / VPS
      # - "${FRONTEND_PUBLIC_PORT:-80}:80"
      # - "443:443"   # if you add certs later
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres:
