services:
  postgres:
    image: postgres:18-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-neohabit}"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-neohabit}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    volumes:
      # NOTE: Saves data locally by default
      # Uncomment the lines at the very bottom if you change the volume to
      # `postgres:/var/lib/postgresql` or similar, note however that
      # `docker compose down -v` will erase all data in that case
      - ./data/postgres:/var/lib/postgresql
    ports:
      # Exposes port 5433 just in case postgres is already running outside docker
      - "127.0.0.1:5433:5432"
    networks:
      - app-network

  backend:
    restart: unless-stopped
    image: ghcr.io/vsein/neohabit-back:${TAG:-latest}
    # uncomment for building manually
    # build: ./backend
    # pull_policy: build
    depends_on:
      postgres:
        condition: service_healthy
    container_name: backend
    environment:
      PG_DSN: postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-password}@postgres:5432/${POSTGRES_DB:-neohabit}?sslmode=disable
      PG_MAX_OPEN_CONNS: ${PG_MAX_OPEN_CONNS:-10}
      PG_MAX_LIFETIME: ${PG_MAX_LIFETIME:-1h}
      PG_MAX_IDLE_TIME: ${PG_MAX_IDLE_TIME:-1h}
      LOG_LEVEL: ${LOG_LEVEL:-info}
      JWT_SECRET: ${JWT_SECRET:-please_DONT_leave_blank}
      FRONTEND_URL: ${FRONTEND_URL:-http://127.0.0.1:8080}
      ADDRESS: ":${BACKEND_PORT:-9000}"
      BACKEND_PORT: ${BACKEND_PORT:-9000}
    ports:
      - :${BACKEND_PORT}
    networks:
      - app-network

  frontend:
    restart: unless-stopped
    image: ghcr.io/vsein/neohabit-front:${TAG:-latest}
    # uncomment for building manually
    # build: ./frontend
    # pull_policy: build
    container_name: frontend
    environment:
      DISABLE_SIGNUP: ${DISABLE_SIGNUP:-false}
      STRICT_USER_FIELDS: ${STRICT_USER_FIELDS:-false}
      REQUIRE_EMAIL: ${REQUIRE_EMAIL:-false}
      DEMO: false
    ports:
      # when localhosting, exposing only 127.0.0.1 is more secure
      # Unless you need LAN access, don't change it
      - "127.0.0.1:${FRONTEND_PORT:-8080}:80"   # local
      # - "${FRONTEND_PORT:-80}:80"               # prod
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

# uncomment if you want to store postgres data in a volume instead
# volumes:
#   postgres:
